# Generated by Django 5.2 on 2025-05-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_user_delete_customuser"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="CustomUser",
        ),
    ]
