# Generated by Django 5.2 on 2025-05-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article_options_alter_article_is_public_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="blog/images",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="view_count",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
